# 工作流的名称，如果省略，则使用当前文件名
name: update to blog

# 从工作流生成的工作流运行的名称，如果省略，则使用提交时的commit信息
run-name: Deploy by @${{ github.actor }}

# 触发部署的条件
on:
  # 每当 push 到 master 分支时触发部署
  push:
    branches: 
      - v1
# 当前流程要执行的任务，可以是多个。[my_first_job]就是一个任务
jobs:
  my_first_job:
    # 任务的名称，不设置则默认my_first_job
    name: build-and-deploy
    # 运行所需要的虚拟机环境
    runs-on: ubuntu-latest
    # 每个任务下的运行步骤，短横杠 - 表示一个步骤，从上至下依次执行。
    steps:
      # clone 该仓库的源码到工作流中
      - name: Clone Code
        uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          # 选择要使用的 node 版本
          node-version: '22'
      - name: TranslateFile
        run: |
          npm install -g pnpm
          pnpm i
          pnpm run build   
      - name: Compress Build Folder
        run: |
          cd ./doc_build
          tar --warning=no-file-changed -czf build.tar.gz .
          cd ..
      # - name: Wait for 2 seconds
      #   run: |
      #     sleep 2
      - name: Upload and Extract on Server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HUAWEI_SERVER_IP }}
          username: ${{ secrets.HUAWEI_USERNAME }}
          password: ${{ secrets.HUAWEI_PASSWORD }}
          port: ${{ secrets.HUAWEI_SERVER_PORT }}
          source: "doc_build/build.tar.gz"
          target: ${{ secrets.SERVER_DESTINATION }}
      - name: Extract Files on Server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.HUAWEI_SERVER_IP }}
          username: ${{ secrets.HUAWEI_USERNAME }}
          password: ${{ secrets.HUAWEI_PASSWORD }}
          port: ${{ secrets.HUAWEI_SERVER_PORT }}
          script: |
            cd ${{ secrets.SERVER_DESTINATION }}
            tar -xzf build.tar.gz
      # - name: 连接服务器
      #   # uses: wangyucode/sftp-upload-action@24f8bb83383dc39bed201ee5da01475e6c38c568
      #   uses: wangyucode/sftp-upload-action@v2.0.2
      #   with:
      #     host: ${{ secrets.HUAWEI_SERVER_IP }} # 你的nginx服务器公网ip
      #     port: ${{ secrets.HUAWEI_SERVER_PORT }} # 你的nginx服务器ssh端口
      #     username: ${{ secrets.HUAWEI_USERNAME }} # 你的nginx服务器用户名
      #     password: ${{ secrets.HUAWEI_PASSWORD }} # 你的nginx服务器密码
      #     localDir: ./doc_build # 你vue项目build好的文件的路径,每次服务器上会自动删除对应的文件夹后重新覆盖
      #     remoteDir: ${{ secrets.SERVER_DESTINATION }} # 你要把你build好的文件夹放到nginx服务器上的什么位置，一般都是nginx配置的站点路径